# This is a basic workflow to help you get started with Actions
name: Push to gh-pages on tag

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: to-deploy-in-gh-pages branch

    - name: Install
      run: npm install

    - name: Echo branch
      run: echo running on branch ${GITHUB_REF##*/}

    - name: Merge master to the to to-deploy-in-gh-pages branch
      run: git merge master

    - name: Push to-deploy-in-gh-pages branch
      run: git push -u origin to-deploy-in-gh-pages branch

    - name: Predeploy
      run: npm run predeploy

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build