# This is a basic workflow to help you get started with Actions
name: Push to gh-pages on tag

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to uat branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'to-deploy-in-gh-pages'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Echo branch
        run: echo running on branch ${GITHUB_REF##*/}

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #     with:
  #       ref: to-deploy-in-gh-pages

  #   - name: Echo branch
  #     run: echo running on branch ${GITHUB_REF##*/}

  #   - name: Install
  #     run: npm install

  #   - name: pull to to-deploy-in-gh-pages branch
  #     run: git pull

  #   - name: Push to-deploy-in-gh-pages branch
  #     run: git push -u origin to-deploy-in-gh-pages

  #   - name: Predeploy
  #     run: npm run predeploy

  #   - name: Deploy
  #     uses: JamesIves/github-pages-deploy-action@releases/v3
  #     with:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       BRANCH: gh-pages
  #       FOLDER: build